### ISSUE TITLE
Error compilation with Qt 6

### ISSUE THREAD

**Issue by ingpconci** [raptorswing/MapGraphics#30]
I've tried to integrate in an application compilet with Qt 6.2.3 but there are some Issues due to API modification.
`new QMutex(QMutex::Recursive); 
error C2039: 'Recursive': is not a member of 'QMutex'
...
QWheelEvent *event
...
event->delta() i s not a member of QWheelEvent 

QRegExp not found
`
I can modify the code in order to adapt for the new API Qt6 and I want to contribute to this interesting project.

Have you got some suggestion in order to maintain the retro compatibility of the code with Qt 5?

**Comment by raptorswing** [comment]
Hi,

I haven't tried compiling for Qt6 yet, but it looks like there are some easy solutions for these specific issues:

For `QMutex(QMutex::Recursive)`, I think `QRecursiveMutex` can be used instead and should work in both Qt5 and Qt6. See https://doc.qt.io/qt-6/qtcore-changes-qt6.html#qmutex-and-related-classes.

For `QWheelEvent`: it looks like `delta()` was considered deprecated even in Qt5 (see https://doc.qt.io/qt-5/qwheelevent-obsolete.html#delta). This is a holdover from Qt4 probably. The docs recommend replacing it with `pixelDelta` or `angleDelta` instead, either of which should exist in both Qt5 and Qt6.

For `QRegExp`, it looks like there's a solution here: https://doc.qt.io/qt-6/qtcore-changes-qt6.html#the-qregexp-class.

These changes might break compatibility with Qt4 - I'm not sure. But Qt4 is old enough now that I'm probably not too worried about keeping compatibility with it.

Alternatively, another option would be to use a compile-time macro like [QT_VERSION_CHECK](https://doc.qt.io/qt-5/qtglobal.html#QT_VERSION_CHECK)

**Comment by ingpconci** [comment]
Thank, I started to modify the code and I choosed the approach with QT_VERSION_CHECK
```
#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
    #include <QtCore5Compat/QRegExp>
#endif
```

```
#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
    QPoint numPixels = event->pixelDelta();
    QPoint numDegrees = event->angleDelta() / 8;

#else
    event->setAccepted(true);
    this->setDragMode(MapGraphicsView::ScrollHandDrag);
    if (event->delta() > 0)
        this->zoomIn(MouseZoom);
    else
        this->zoomOut(MouseZoom);
#endif
```

But non I found a strange bug 
With Qt MSVC 2019:

Qt\6.2.3\msvc2019_64\include\QtCore/qhash.h(100): error C2338: The key type must have a qHash overload or a std::hash specialization
...
Qt\6.2.3\msvc2019_64\include\QtCore/qset.h(240): note: vedere il riferimento all'istanza 'QHash<T,QHashDummyValue>' di modello classe di cui Š in corso la compilazione
        with
        [
            T=QPointF
        ]
..\..\MapGraphics\MapGraphics\MapGraphicsView.cpp(434): note: vedere il riferimento all'istanza **'QSet<QPointF>**' 

With Android 
Qt\6.2.3\android_x86_64\include\QtCore/qhash.h:100:9: error: static_assert failed due to requirement 'sizeof(QPointF) == 0' "The key type must have a qHash overload or a std::hash specialization"
        static_assert(sizeof(T) == 0, "The key type must have a qHash overload or a std::hash specialization");
Qt\6.2.3\android_x86_64\include\QtCore/qset.h:194:25: note: in instantiation of function template specialization 'QHash<QPointF, QHashDummyValue>::emplace<QHashDummyValue>' requested here
        { return q_hash.emplace(std::move(value), QHashDummyValue()); }
                        ^
..\..\MapGraphics\MapGraphics\MapGraphicsView.cpp:443:33: note: in instantiation of member function 'QSet<QPointF>::insert' requested here
            placesWhereTilesAre.insert(tileObject->pos());


I found that perhaps I need to implement some missing function for type PointF
[](https://doc.qt.io/qt-6/qhash.html#qhash)

It's better to change the container for the tiles using another key type?

 `QSet<QPointF> placesWhereTilesAre;
`

**Comment by ingpconci** [comment]
I finish to make changes to compile with Qt 6.2.3.
I modified the code and test the app with:
- MSVC2019_64bit to make a Win executable on Win10
- Android Clang_x86_64 to test in Android Emulator  (No zoom features)
- Android Clang_arm64-v8a and tested on an Huawey P10 lite Android 8 (No zoom features)

Now I want to implement the Zoom features on Android device with touch ui and use two finger zoom.
I add a event to manage the touch event (copied from Qt example pinchzoom

```
bool MapGraphicsView::handleChildViewportEvent(QEvent *event)
{
    event->setAccepted(true);
    this->setDragMode(MapGraphicsView::NoDrag);

    switch (event->type()) {
    case QEvent::TouchBegin:
    case QEvent::TouchUpdate:
    case QEvent::TouchEnd:
    {
        QTouchEvent *touchEvent = static_cast<QTouchEvent *>(event);
        const auto touchPoints = touchEvent->points();
        if (touchPoints.count() == 2) {
            // determine scale factor
            const QEventPoint &touchPoint0 = touchPoints.first();
            const QEventPoint &touchPoint1 = touchPoints.last();
            qreal currentScaleFactor =
                    QLineF(touchPoint0.position(), touchPoint1.position()).length()
                    / QLineF(touchPoint0.pressPosition(), touchPoint1.pressPosition()).length();
            if (touchEvent->touchPointStates() & QEventPoint::Released) {
                // if one of the fingers is released, remember the current scale
                // factor so that adding another finger later will continue zooming
                // by adding new scale factor to the existing remembered value.
                totalScaleFactor *= currentScaleFactor;
                currentScaleFactor = 1;
            }
            qDebug()<<"MapGraphicsView::handleChildViewportEvent: currentScaleFactor="<<currentScaleFactor<<" totalScaleFactor="<<totalScaleFactor;
            //setTransform(QTransform::fromScale(totalScaleFactor * currentScaleFactor,totalScaleFactor * currentScaleFactor));

            if ((totalScaleFactor * currentScaleFactor)>1) {
                this->zoomIn(MouseZoom);
            } else {
                this->zoomOut(MouseZoom);
            }
        }
        return true;
    }
    default:
        break;
    }
    //return QGraphicsView::viewportEvent(event);
    return false;
}
```
Have you got some suggestion for the zoom function applied to touch event?

When I finished this function I want to complete with a compilation with XCode for iOs.

How I can submit my modification to the github MapGraphics repository?

**Comment by raptorswing** [comment]
Hi,

The best way to get changes into this repository is to fork it, make the changes in a working branch of your fork, and then send a pull request (PR) to this repository. Then we can review the changes and get them merged in. Please do one PR for the Qt6 compatibility changes and one PR for the pinch zoom. 

Regarding the pinch zoom touch event - the code you've shared seems reasonable, but I haven't done any work with touch in Qt and so I'm not in a good position to know if there's an easier or better way.
